[package]
name = "firewood-benchmark"
version = "0.0.6"
edition = "2024"
rust-version = "1.85.0"
authors = [
     "Aaron Buchwald <aaron.buchwald56@gmail.com>",
     "Ron Kuris <ron.kuris@avalabs.org>",
]
description = "Benchmarking tool for Firewood, an embedded key-value store optimized for blockchain state."
license-file = "../LICENSE.md"
homepage = "https://avalabs.org"
repository = "https://github.com/ava-labs/firewood"

[[bin]]
name = "benchmark"
path = "src/main.rs"

[dependencies]
firewood = { version = "0.0.6", path = "../firewood" }
hex = "0.4.3"
clap = { version = "4.5.0", features = ['derive', 'string'] }
sha2 = "0.10.8"
metrics = "0.24.2"
metrics-util = "0.20.0"
metrics-exporter-prometheus = "0.17.2"
tokio = { version = "1.36.0", features = ["rt", "sync", "macros", "rt-multi-thread"] }
rand = "0.9.0"
rand_distr = "0.5.0"
pretty-duration = "0.1.1"
env_logger = "0.11.5"
log = "0.4.20"
fastrace = { version = "0.7.4", features = ["enable"] }
fastrace-opentelemetry = { version = "0.12.0" }
opentelemetry-otlp = { version = "0.30.0", features = ["grpc-tonic"] }
opentelemetry = "0.30.0"
opentelemetry_sdk = "0.30.0"
strum = "0.27.0"

[target.'cfg(unix)'.dependencies]
tikv-jemallocator = "0.6.0"

[features]
logger = ["firewood/logger"]

[lints]
workspace = true
