[package]
name = "benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
firewood = { path = "../firewood" }
hex = "0.4.3"
clap = { version = "4.5.0", features = ['derive', 'string'] }
sha2 = "0.10.8"
metrics = "0.24.1"
metrics-util = "0.19.0"
metrics-exporter-prometheus = "0.16.1"
tokio = { version = "1.36.0", features = ["rt", "sync", "macros", "rt-multi-thread"] }
rand = "0.8.5"
pretty-duration = "0.1.1"
tikv-jemallocator = "0.6.0"
env_logger = "0.11.5"
zipf = "7.0.1"
log = "0.4.20"
fastrace = { version = "0.7.4", features = ["enable"] }
fastrace-opentelemetry = { version = "0.8.0" }
opentelemetry-otlp = "0.27.0"
opentelemetry = "0.27.0"
opentelemetry_sdk = "0.27.1"

[features]
logger = ["firewood/logger"]
