# https://golangci-lint.run/usage/configuration/
run:
  timeout: 10m

  # If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #
  # Allowed values: readonly|vendor|mod
  # By default, it isn't set.
  modules-download-mode: readonly

issues:
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: false

  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0

  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0

  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  exclude-dirs-use-default: false

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dupword
    - dupl
    - errcheck
    - errname
    - errorlint
    - forbidigo
    - gci
    - goconst
    - gocritic
    # - err113 - encourages wrapping static errors
    - gofmt
    - gofumpt
    # - mnd - unnecessary magic numbers
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    # - lll line length linter
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - spancheck
    - staticcheck
    - stylecheck
    - tagalign
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

linters-settings:
  depguard:
    rules:
      packages:
        deny:
          - pkg: "github.com/golang/mock/gomock"
            desc: go.uber.org/mock/gomock should be used instead.
          - pkg: "github.com/stretchr/testify/assert"
            desc: github.com/stretchr/testify/require should be used instead.
          - pkg: "io/ioutil"
            desc: io/ioutil is deprecated. Use package io or os instead.
  errorlint:
    # Check for plain type assertions and type switches.
    asserts: false
    # Check for plain error comparisons.
    comparison: false
  forbidigo:
    # Forbid the following identifiers (list of regexp).
    forbid:
      - 'require\.Error$(# ErrorIs should be used instead)?'
      - 'require\.ErrorContains$(# ErrorIs should be used instead)?'
      - 'require\.EqualValues$(# Equal should be used instead)?'
      - 'require\.NotEqualValues$(# NotEqual should be used instead)?'
      - '^(t|b|tb|f)\.(Fatal|Fatalf|Error|Errorf)$(# the require library should be used instead)?'
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#bool-literal-in-expr
      - name: bool-literal-in-expr
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return
      - name: early-return
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#empty-lines
      - name: empty-lines
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#string-format
      - name: string-format
        disabled: false
        arguments:
        - ["b.Logf[0]", "/.*%.*/", "no format directive, use b.Log instead"]
        - ["fmt.Errorf[0]", "/.*%.*/", "no format directive, use errors.New instead"]
        - ["fmt.Fprintf[1]", "/.*%.*/", "no format directive, use fmt.Fprint instead"]
        - ["fmt.Printf[0]", "/.*%.*/", "no format directive, use fmt.Print instead"]
        - ["fmt.Sprintf[0]", "/.*%.*/", "no format directive, use fmt.Sprint instead"]
        - ["log.Fatalf[0]", "/.*%.*/", "no format directive, use log.Fatal instead"]
        - ["log.Printf[0]", "/.*%.*/", "no format directive, use log.Print instead"]
        - ["t.Logf[0]", "/.*%.*/", "no format directive, use t.Log instead"]
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#struct-tag
      - name: struct-tag
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unexported-naming
      - name: unexported-naming
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unhandled-error
      - name: unhandled-error
        # prefer the errcheck linter since it can be disabled directly with nolint directive
        # but revive's disable directive (e.g. //revive:disable:unhandled-error) is not
        # supported when run under golangci_lint
        disabled: true
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-parameter
      - name: unused-parameter
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unused-receiver
      - name: unused-receiver
        disabled: false
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#useless-break
      - name: useless-break
        disabled: false
  tagalign:
    align: true
    sort: true
    strict: true
    order:
      - serialize
  testifylint:
    # Enable all checkers (https://github.com/Antonboom/testifylint#checkers).
    # Default: false
    enable-all: true
    # Disable checkers by name
    # (in addition to default
    #   suite-thelper
    # ).
    disable:
      - go-require
      - float-compare
