// Copyright (C) 2025, Ava Labs, Inc. All rights reserved.
// See the file LICENSE.md for licensing terms.

package ffi

// #include <stdlib.h>
// #include "firewood.h"
// #cgo noescape fwd_db_range_proof
// #cgo nocallback fwd_db_range_proof
// #cgo noescape fwd_db_range_proof_from_bytes
// #cgo nocallback fwd_db_range_proof_from_bytes
// #cgo noescape fwd_db_verify_range_proof
// #cgo nocallback fwd_db_verify_range_proof
// #cgo noescape fwd_range_proof_to_bytes
// #cgo nocallback fwd_range_proof_to_bytes
// #cgo noescape fwd_verified_range_proof_commit
// #cgo nocallback fwd_verified_range_proof_commit
// #cgo noescape fwd_verified_range_proof_next_key_ranges
// #cgo nocallback fwd_verified_range_proof_next_key_ranges
// #cgo noescape fwd_verified_range_proof_code_hash_iter
// #cgo nocallback fwd_verified_range_proof_code_hash_iter
// #cgo noescape fwd_db_change_proof
// #cgo nocallback fwd_db_change_proof
// #cgo noescape fwd_db_change_proof_from_bytes
// #cgo nocallback fwd_db_change_proof_from_bytes
// #cgo noescape fwd_db_verify_change_proof
// #cgo nocallback fwd_db_verify_change_proof
// #cgo noescape fwd_change_proof_to_bytes
// #cgo nocallback fwd_change_proof_to_bytes
// #cgo noescape fwd_verified_change_proof_commit
// #cgo nocallback fwd_verified_change_proof_commit
// #cgo noescape fwd_verified_change_proof_next_key_ranges
// #cgo nocallback fwd_verified_change_proof_next_key_ranges
// #cgo noescape fwd_verified_change_proof_code_hash_iter
// #cgo nocallback fwd_verified_change_proof_code_hash_iter
// #cgo noescape fwd_code_hash_iter_next
// #cgo nocallback fwd_code_hash_iter_next
// #cgo noescape fwd_code_hash_iter_free
// #cgo nocallback fwd_code_hash_iter_free
// #cgo noescape fwd_free_next_key_ranges
// #cgo nocallback fwd_free_next_key_ranges
// #cgo noescape fwd_free_range_proof
// #cgo nocallback fwd_free_range_proof
// #cgo noescape fwd_free_verified_range_proof
// #cgo nocallback fwd_free_verified_range_proof
// #cgo noescape fwd_free_change_proof
// #cgo nocallback fwd_free_change_proof
// #cgo noescape fwd_free_verified_change_proof
// #cgo nocallback fwd_free_verified_change_proof
import "C"

import (
	"errors"
	"fmt"
	"runtime"
	"time"
	"unsafe"
)

var (
	errEmptyTrie          = errors.New("a range proof was requested on an empty trie")
	errDroppedRangeProof  = fmt.Errorf("range proof %w", ErrDropped)
	errDroppedChangeProof = fmt.Errorf("change proof %w", ErrDropped)
)

// RangeProof is a proof that a range of keys and their values are included in
// a trie with a given root hash, as produced by [Database.RangeProof] or
// parsed by [Database.UnmarshalRangeProof].
//
// A RangeProof is portable: it holds no lease on its database, never blocks
// [Database.Close], and [RangeProof.Marshal] keeps working after the database
// is closed. It knows which database it belongs to only so that
// [RangeProof.Verify] can check it there and produce a [VerifiedRangeProof].
type RangeProof struct {
	// handle owns the Rust RangeProofContext. Its lease is never attached to a
	// registry; lease.mu only serializes method calls against Drop, which frees
	// the context (see https://github.com/ava-labs/firewood/issues/2137). No C
	// function takes the context mutably, so every method holds lease.mu.RLock.
	*handle[*C.RangeProofContext]

	// db is the database this proof was generated by or parsed for.
	db *Database
}

// VerifiedRangeProof is a [RangeProof] that [RangeProof.Verify] checked against
// a root hash on one database. It owns the proposal that applies the proof
// there, so it holds that database's keep-alive lease from construction until
// [VerifiedRangeProof.Drop]: [Database.Close] waits for it, and
// [WithForceCloseHandles] drops it.
type VerifiedRangeProof struct {
	// handle owns the Rust VerifiedRangeProofContext and the lease. Commit takes
	// the context mutably and holds lease.mu.Lock; the other methods hold RLock.
	*handle[*C.VerifiedRangeProofContext]

	// db is the database the proof was verified against and commits to.
	db *Database
}

// ChangeProof is a proof of the changes between two roots for a range of keys,
// as produced by [Database.ChangeProof] or parsed by
// [Database.UnmarshalChangeProof]. It is portable on the same terms as
// [RangeProof].
type ChangeProof struct {
	// handle owns the Rust ChangeProofContext, under the same rules as
	// [RangeProof].
	*handle[*C.ChangeProofContext]

	// db is the database this proof was generated by or parsed for.
	db *Database
}

// VerifiedChangeProof is a [ChangeProof] that [ChangeProof.Verify] checked
// against an end root on one database. It holds that database's lease on the
// same terms as [VerifiedRangeProof].
type VerifiedChangeProof struct {
	*handle[*C.VerifiedChangeProofContext]

	db *Database
}

// NextKeyRange is a range of keys still to fetch, `[StartKey, EndKey]`, both
// inclusive. StartKey is the first key of a span whose content the database
// does not hold the way the target does; passing it as the next request's
// start key resumes there. If EndKey has no value, the range is unbounded
// above.
//
// The keys are Go-owned copies; a NextKeyRange needs no release.
type NextKeyRange struct {
	StartKey []byte
	EndKey   Maybe[[]byte]
}

// codeIterator wraps a Rust CodeIteratorHandle<'p>, a Box<dyn Iterator + 'p>
// over the entries of the verified proof it was created from. The proof's
// read lock is held for the iterator's whole life by the CodeHashes method
// that drains it.
type codeIterator struct {
	handle *C.CodeIteratorHandle
}

// RangeProof returns a proof that the values in the range [startKey, endKey]
// are included in the tree with root [rootHash]. The proof may be truncated to
// at most [maxLength] entries, if non-zero. If either [startKey] or [endKey]
// is Nothing, the range is unbounded in that direction.
//
// The result is unverified. A producer serializes it with
// [RangeProof.Marshal]; a consumer parses it with
// [Database.UnmarshalRangeProof] and checks it with [RangeProof.Verify].
func (db *Database) RangeProof(
	rootHash Hash,
	startKey, endKey Maybe[[]byte],
	maxLength uint32,
) (*RangeProof, error) {
	db.handleLock.RLock()
	defer db.handleLock.RUnlock()
	if db.handle == nil {
		return nil, errDBClosed
	}

	var pinner runtime.Pinner
	defer pinner.Unpin()

	args := C.CreateRangeProofArgs{
		root:       newCHashKey(rootHash),
		start_key:  newMaybeBorrowedBytes(startKey, &pinner),
		end_key:    newMaybeBorrowedBytes(endKey, &pinner),
		max_length: C.uint32_t(maxLength),
	}

	return db.newRangeProof(C.fwd_db_range_proof(db.handle, args))
}

// UnmarshalRangeProof parses a proof produced by [RangeProof.Marshal] for use
// with db. A proof encoded for the other hash mode is rejected here, before
// any verification.
func (db *Database) UnmarshalRangeProof(data []byte) (*RangeProof, error) {
	db.handleLock.RLock()
	defer db.handleLock.RUnlock()
	if db.handle == nil {
		return nil, errDBClosed
	}

	start := time.Now()
	defer func() {
		proofUnmarshalDuration.WithLabelValues("range", db.metricsTag).Observe(time.Since(start).Seconds())
	}()

	var pinner runtime.Pinner
	defer pinner.Unpin()
	return db.newRangeProof(C.fwd_db_range_proof_from_bytes(db.handle, newBorrowedBytes(data, &pinner)))
}

// Verify checks that the proof proves the values in the range [startKey,
// endKey] are included in the tree with root [rootHash], under the hash mode of
// the database the proof belongs to, and prepares the proposal that applies it
// to that database's latest revision.
//
// The proposal brings the database into agreement with the proof's target
// everywhere the proof speaks. Across the range the proof proves — from
// [startKey] to the proof's right edge, which is [endKey] when the responder
// covered the whole request and a smaller key when it truncated — state is
// replaced: any existing key there that the proof does not carry is deleted.
// Outside that range the proof's boundary hashes settle some of the key space
// too: content the target does not hold is deleted, and keys whose target
// value the proof carries are written. What they cannot settle is what
// [VerifiedRangeProof.NextKeyRanges] reports as still to fetch.
//
// Verify does not consume the proof: it stays usable for [RangeProof.Marshal]
// or for another Verify. Each successful call builds its own proposal, so a
// caller that wants one verified proof keeps the one it was handed rather than
// calling Verify again. A failed Verify builds nothing.
//
// Verify does not take the database's commit lock, unlike [Database.Propose].
// The proposal it builds is pinned to the latest revision at the time of the
// call; if a commit lands first, [VerifiedRangeProof.Commit] rebuilds the
// proposal from the proof.
//
// Returns an error once the database is closed, and a dropped-proof error
// wrapping [ErrDropped] once the proof is dropped.
func (p *RangeProof) Verify(
	rootHash Hash,
	startKey, endKey Maybe[[]byte],
	maxLength uint32,
) (*VerifiedRangeProof, error) {
	p.db.handleLock.RLock()
	defer p.db.handleLock.RUnlock()
	if p.db.handle == nil {
		return nil, errDBClosed
	}

	p.lease.mu.RLock()
	defer p.lease.mu.RUnlock()
	if p.dropped {
		return nil, errDroppedRangeProof
	}

	var pinner runtime.Pinner
	defer pinner.Unpin()

	args := C.VerifyRangeProofArgs{
		root:       newCHashKey(rootHash),
		start_key:  newMaybeBorrowedBytes(startKey, &pinner),
		end_key:    newMaybeBorrowedBytes(endKey, &pinner),
		max_length: C.uint32_t(maxLength),
	}

	return p.db.newVerifiedRangeProof(C.fwd_db_verify_range_proof(p.db.handle, p.ptr, args))
}

// Marshal returns a serialized representation of this RangeProof.
//
// The format is unspecified and opaque to firewood. Marshal makes no database
// call, so it keeps working after the database is closed.
func (p *RangeProof) Marshal() ([]byte, error) {
	p.lease.mu.RLock()
	defer p.lease.mu.RUnlock()
	if p.dropped {
		return nil, errDroppedRangeProof
	}

	start := time.Now()
	defer func() {
		proofMarshalDuration.WithLabelValues("range").Observe(time.Since(start).Seconds())
	}()

	return getValueFromValueResult(C.fwd_range_proof_to_bytes(p.ptr))
}

// Commit applies the proof to the database and returns the new root hash,
// which may differ from the verified root when the proof was truncated. The
// proposal is the one [RangeProof.Verify] describes: the proven range is
// replaced and the walk's local remedies outside it are written.
//
// A prepared proposal is committed as-is. If the database advanced since
// Verify, the proposal is rebuilt from the proof and committed. A second
// Commit returns the same root without touching the database. Commit does not
// consume the proof, and it does not release the lease; call
// [VerifiedRangeProof.Drop] for that.
//
// Commit locks the latest state of the database, so it blocks against
// [Database.Update], [Database.Propose], and other commits.
func (p *VerifiedRangeProof) Commit() (Hash, error) {
	// Write lock: fwd_verified_range_proof_commit takes the context mutably.
	p.lease.mu.Lock()
	defer p.lease.mu.Unlock()
	if p.dropped {
		return EmptyRoot, errDroppedRangeProof
	}

	p.db.commitLock.Lock()
	defer p.db.commitLock.Unlock()
	return getHashKeyFromHashResult(C.fwd_verified_range_proof_commit(p.ptr))
}

// NextKeyRanges returns the key ranges still to fetch after this proof, sorted
// ascending by start key and coalesced where adjacent. The answer describes
// the database's latest committed revision as of the call (a commit racing
// the call is reflected by one side of the comparison or the other): the
// proof's boundary hashes are compared against it, and every span of key
// space outside the proven range whose target content the database lacks or
// holds differently becomes a range. The boundary proofs speak for the whole
// key space, so ranges are not confined to the request's bounds: they may lie
// below its start key or above its end key. An empty result means nothing
// remains: the proof covered the request, or the database's root already
// equals the verified root.
//
// Each range is `[StartKey, EndKey]`, both inclusive. EndKey covers one key
// more than strictly needed — the first key of whatever follows the holes —
// because a span of the key space has no exact inclusive upper bound; a
// reply over the range rewrites or deletes that key exactly as the target
// holds it, so the extra key is harmless.
func (p *VerifiedRangeProof) NextKeyRanges() ([]NextKeyRange, error) {
	p.lease.mu.RLock()
	defer p.lease.mu.RUnlock()
	if p.dropped {
		return nil, errDroppedRangeProof
	}
	return getNextKeyRangesFromResult(C.fwd_verified_range_proof_next_key_ranges(p.ptr))
}

// CodeHashes returns the contract code hashes referenced by the account values
// in this proof, in no particular order and possibly with duplicates.
//
// Only Ethereum-mode databases have account values; on a merkledb-mode database
// this returns an error. The hashes come from a verified proof, so a caller may
// act on them (for example, fetch the code) without further checks.
func (p *VerifiedRangeProof) CodeHashes() ([]Hash, error) {
	p.lease.mu.RLock()
	defer p.lease.mu.RUnlock()
	if p.dropped {
		return nil, errDroppedRangeProof
	}
	return collectCodeHashes(C.fwd_verified_range_proof_code_hash_iter(p.ptr))
}

// ChangeProof returns a proof of the changes between [startRoot] and [endRoot]
// for keys in the range [startKey, endKey]. The proof may be truncated to at
// most [maxLength] entries, if non-zero. If either [startKey] or [endKey] is
// Nothing, the range is unbounded in that direction.
//
// The result is unverified; see [Database.RangeProof] for the producer and
// consumer flow.
func (db *Database) ChangeProof(
	startRoot, endRoot Hash,
	startKey, endKey Maybe[[]byte],
	maxLength uint32,
) (*ChangeProof, error) {
	db.handleLock.RLock()
	defer db.handleLock.RUnlock()
	if db.handle == nil {
		return nil, errDBClosed
	}

	var pinner runtime.Pinner
	defer pinner.Unpin()

	args := C.CreateChangeProofArgs{
		start_root: newCHashKey(startRoot),
		end_root:   newCHashKey(endRoot),
		start_key:  newMaybeBorrowedBytes(startKey, &pinner),
		end_key:    newMaybeBorrowedBytes(endKey, &pinner),
		max_length: C.uint32_t(maxLength),
	}

	return db.newChangeProof(C.fwd_db_change_proof(db.handle, args))
}

// UnmarshalChangeProof parses a proof produced by [ChangeProof.Marshal] for use
// with db. A proof encoded for the other hash mode is rejected here, before
// any verification.
func (db *Database) UnmarshalChangeProof(data []byte) (*ChangeProof, error) {
	db.handleLock.RLock()
	defer db.handleLock.RUnlock()
	if db.handle == nil {
		return nil, errDBClosed
	}

	start := time.Now()
	defer func() {
		proofUnmarshalDuration.WithLabelValues("change", db.metricsTag).Observe(time.Since(start).Seconds())
	}()

	var pinner runtime.Pinner
	defer pinner.Unpin()
	return db.newChangeProof(C.fwd_db_change_proof_from_bytes(db.handle, newBorrowedBytes(data, &pinner)))
}

// Verify checks the proof structurally, applies its changes to the latest
// revision of the database the proof belongs to, and checks that the result
// matches [endRoot] across [startKey, endKey]. The proposal also applies, outside
// that range, the local remedies the proof's boundary hashes justify: content
// the target does not hold is deleted and keys whose target value the proof
// carries are written. On success the prepared proposal is held by the
// returned [VerifiedChangeProof].
//
// Verify does not consume the proof; see [RangeProof.Verify] for the cost of
// calling it more than once and for why it does not take the database's
// commit lock. Returns an error once the database is closed, and a
// dropped-proof error wrapping [ErrDropped] once the proof is dropped.
func (p *ChangeProof) Verify(
	endRoot Hash,
	startKey, endKey Maybe[[]byte],
	maxLength uint32,
) (*VerifiedChangeProof, error) {
	p.db.handleLock.RLock()
	defer p.db.handleLock.RUnlock()
	if p.db.handle == nil {
		return nil, errDBClosed
	}

	p.lease.mu.RLock()
	defer p.lease.mu.RUnlock()
	if p.dropped {
		return nil, errDroppedChangeProof
	}

	var pinner runtime.Pinner
	defer pinner.Unpin()

	args := C.VerifyChangeProofArgs{
		end_root:   newCHashKey(endRoot),
		start_key:  newMaybeBorrowedBytes(startKey, &pinner),
		end_key:    newMaybeBorrowedBytes(endKey, &pinner),
		max_length: C.uint32_t(maxLength),
	}

	return p.db.newVerifiedChangeProof(C.fwd_db_verify_change_proof(p.db.handle, p.ptr, args))
}

// Marshal returns a serialized representation of this ChangeProof.
//
// The format is unspecified and opaque to firewood. Marshal makes no database
// call, so it keeps working after the database is closed.
func (p *ChangeProof) Marshal() ([]byte, error) {
	p.lease.mu.RLock()
	defer p.lease.mu.RUnlock()
	if p.dropped {
		return nil, errDroppedChangeProof
	}

	start := time.Now()
	defer func() {
		proofMarshalDuration.WithLabelValues("change").Observe(time.Since(start).Seconds())
	}()

	return getValueFromValueResult(C.fwd_change_proof_to_bytes(p.ptr))
}

// Commit applies the proof to the database and returns the new root hash.
// The proposal is the one [ChangeProof.Verify] describes: the proof's
// operations are applied and the walk's local remedies outside the proven
// range are written.
//
// If the database advanced since Verify, Commit verifies the proof again
// against the current latest revision and commits from there, so the proven
// range is checked against the verified end root on the state it lands on
// rather than rebased blindly. A second Commit returns the same root without
// touching the database. Commit does not consume the proof and does not
// release the lease; call [VerifiedChangeProof.Drop] for that.
//
// Commit locks the latest state of the database on the same terms as
// [VerifiedRangeProof.Commit].
func (p *VerifiedChangeProof) Commit() (Hash, error) {
	// Write lock: fwd_verified_change_proof_commit takes the context mutably.
	p.lease.mu.Lock()
	defer p.lease.mu.Unlock()
	if p.dropped {
		return EmptyRoot, errDroppedChangeProof
	}

	p.db.commitLock.Lock()
	defer p.db.commitLock.Unlock()
	return getHashKeyFromHashResult(C.fwd_verified_change_proof_commit(p.ptr))
}

// NextKeyRanges returns the key ranges still to fetch after this proof, on the
// same terms as [VerifiedRangeProof.NextKeyRanges].
func (p *VerifiedChangeProof) NextKeyRanges() ([]NextKeyRange, error) {
	p.lease.mu.RLock()
	defer p.lease.mu.RUnlock()
	if p.dropped {
		return nil, errDroppedChangeProof
	}
	return getNextKeyRangesFromResult(C.fwd_verified_change_proof_next_key_ranges(p.ptr))
}

// CodeHashes returns the contract code hashes referenced by the account values
// this proof puts, on the same terms as [VerifiedRangeProof.CodeHashes].
// Delete and DeleteRange entries are skipped.
func (p *VerifiedChangeProof) CodeHashes() ([]Hash, error) {
	p.lease.mu.RLock()
	defer p.lease.mu.RUnlock()
	if p.dropped {
		return nil, errDroppedChangeProof
	}
	return collectCodeHashes(C.fwd_verified_change_proof_code_hash_iter(p.ptr))
}

// collectCodeHashes drains and frees a Rust code-hash iterator. The caller
// holds the owning proof's read lock for the duration.
func collectCodeHashes(result C.CodeIteratorResult) ([]Hash, error) {
	it, err := newCodeIterator(result)
	if err != nil {
		return nil, err
	}

	var hashes []Hash
	for {
		hash, ok, err := it.next()
		if err != nil {
			return nil, errors.Join(err, it.free())
		}
		if !ok {
			break
		}
		hashes = append(hashes, hash)
	}
	if err := it.free(); err != nil {
		return nil, err
	}
	return hashes, nil
}

// next returns the next code hash, or ok == false once the iterator is
// exhausted. Exhaustion is read from the result tag, not from the hash value,
// so an all-zero code hash in the proof is not mistaken for the end.
func (it *codeIterator) next() (hash Hash, ok bool, err error) {
	result := C.fwd_code_hash_iter_next(it.handle)
	if result.tag == C.HashResult_None {
		return EmptyRoot, false, nil
	}
	hash, err = getHashKeyFromHashResult(result)
	if err != nil {
		return EmptyRoot, false, err
	}
	return hash, true, nil
}

// free releases the Rust iterator, ending its borrow of the proof.
func (it *codeIterator) free() error {
	return getErrorFromVoidResult(C.fwd_code_hash_iter_free(it.handle))
}

func newCodeIterator(result C.CodeIteratorResult) (*codeIterator, error) {
	switch result.tag {
	case C.CodeIteratorResult_NullHandlePointer:
		return nil, errDBClosed
	case C.CodeIteratorResult_Ok:
		ptr := *(**C.CodeIteratorHandle)(unsafe.Pointer(&result.anon0))
		return &codeIterator{handle: ptr}, nil
	case C.CodeIteratorResult_Err:
		return nil, newOwnedBytes(*(*C.OwnedBytes)(unsafe.Pointer(&result.anon0))).intoError()
	default:
		return nil, fmt.Errorf("unknown C.CodeIteratorResult tag: %d", result.tag)
	}
}

// getNextKeyRangesFromResult copies the ranges into Go memory and frees the
// Rust list, so the returned values outlive every C allocation.
func getNextKeyRangesFromResult(result C.NextKeyRangesResult) ([]NextKeyRange, error) {
	switch result.tag {
	case C.NextKeyRangesResult_NullHandlePointer:
		return nil, errDBClosed
	case C.NextKeyRangesResult_Ok:
		owned := *(*C.OwnedSlice_NextKeyRange)(unsafe.Pointer(&result.anon0))
		ranges := copyNextKeyRanges(owned)
		if err := getErrorFromVoidResult(C.fwd_free_next_key_ranges(owned)); err != nil {
			return nil, fmt.Errorf("%w: %w", errFreeingValue, err)
		}
		return ranges, nil
	case C.NextKeyRangesResult_Err:
		return nil, newOwnedBytes(*(*C.OwnedBytes)(unsafe.Pointer(&result.anon0))).intoError()
	default:
		return nil, fmt.Errorf("unknown C.NextKeyRangesResult tag: %d", result.tag)
	}
}

func copyNextKeyRanges(owned C.OwnedSlice_NextKeyRange) []NextKeyRange {
	if owned.ptr == nil || owned.len == 0 {
		return nil
	}
	cRanges := unsafe.Slice(owned.ptr, owned.len)
	ranges := make([]NextKeyRange, len(cRanges))
	for i := range cRanges {
		c := &cRanges[i]
		ranges[i].StartKey = newOwnedBytes(c.start_key).CopiedBytes()
		if c.end_key.tag == C.Maybe_OwnedBytes_Some_OwnedBytes {
			endKey := newOwnedBytes(*(*C.OwnedBytes)(unsafe.Pointer(&c.end_key.anon0)))
			ranges[i].EndKey = Some(endKey.CopiedBytes())
		} else {
			ranges[i].EndKey = Nothing[[]byte]()
		}
	}
	return ranges
}

func (db *Database) newRangeProof(result C.RangeProofResult) (*RangeProof, error) {
	switch result.tag {
	case C.RangeProofResult_NullHandlePointer:
		return nil, errDBClosed
	case C.RangeProofResult_RevisionNotFound:
		// NOTE: the result value contains the provided root hash, we could use
		// it in the error message if needed.
		return nil, ErrRevisionNotFound
	case C.RangeProofResult_EmptyTrie:
		return nil, errEmptyTrie
	case C.RangeProofResult_Ok:
		ptr := *(**C.RangeProofContext)(unsafe.Pointer(&result.anon0))
		proof := &RangeProof{
			handle: newHandle(ptr, func(p *C.RangeProofContext) C.VoidResult { return C.fwd_free_range_proof(p) }),
			db:     db,
		}
		runtime.AddCleanup(proof, drop[*C.RangeProofContext], proof.handle)
		return proof, nil
	case C.RangeProofResult_Err:
		return nil, newOwnedBytes(*(*C.OwnedBytes)(unsafe.Pointer(&result.anon0))).intoError()
	default:
		return nil, fmt.Errorf("unknown C.RangeProofResult tag: %d", result.tag)
	}
}

// newVerifiedRangeProof attaches the lease under the caller's
// db.handleLock.RLock, as [getProposalFromProposalResult] does.
func (db *Database) newVerifiedRangeProof(result C.VerifiedRangeProofResult) (*VerifiedRangeProof, error) {
	switch result.tag {
	case C.VerifiedRangeProofResult_NullHandlePointer:
		return nil, errDBClosed
	case C.VerifiedRangeProofResult_Ok:
		ptr := *(**C.VerifiedRangeProofContext)(unsafe.Pointer(&result.anon0))
		proof := &VerifiedRangeProof{
			handle: newHandle(ptr, func(p *C.VerifiedRangeProofContext) C.VoidResult {
				return C.fwd_free_verified_range_proof(p)
			}),
			db: db,
		}
		if err := proof.lease.attach(db.keepAlives, proof.Drop); err != nil {
			return nil, err
		}
		runtime.AddCleanup(proof, drop[*C.VerifiedRangeProofContext], proof.handle)
		return proof, nil
	case C.VerifiedRangeProofResult_Err:
		return nil, newOwnedBytes(*(*C.OwnedBytes)(unsafe.Pointer(&result.anon0))).intoError()
	default:
		return nil, fmt.Errorf("unknown C.VerifiedRangeProofResult tag: %d", result.tag)
	}
}

func (db *Database) newChangeProof(result C.ChangeProofResult) (*ChangeProof, error) {
	switch result.tag {
	case C.ChangeProofResult_NullHandlePointer:
		return nil, errDBClosed
	case C.ChangeProofResult_StartRevisionNotFound:
		return nil, ErrStartRevisionNotFound
	case C.ChangeProofResult_EndRevisionNotFound:
		return nil, ErrEndRevisionNotFound
	case C.ChangeProofResult_Ok:
		ptr := *(**C.ChangeProofContext)(unsafe.Pointer(&result.anon0))
		proof := &ChangeProof{
			handle: newHandle(ptr, func(p *C.ChangeProofContext) C.VoidResult { return C.fwd_free_change_proof(p) }),
			db:     db,
		}
		runtime.AddCleanup(proof, drop[*C.ChangeProofContext], proof.handle)
		return proof, nil
	case C.ChangeProofResult_Err:
		return nil, newOwnedBytes(*(*C.OwnedBytes)(unsafe.Pointer(&result.anon0))).intoError()
	default:
		return nil, fmt.Errorf("unknown C.ChangeProofResult tag: %d", result.tag)
	}
}

// newVerifiedChangeProof attaches the lease under the caller's
// db.handleLock.RLock, as [getProposalFromProposalResult] does.
func (db *Database) newVerifiedChangeProof(result C.VerifiedChangeProofResult) (*VerifiedChangeProof, error) {
	switch result.tag {
	case C.VerifiedChangeProofResult_NullHandlePointer:
		return nil, errDBClosed
	case C.VerifiedChangeProofResult_Ok:
		ptr := *(**C.VerifiedChangeProofContext)(unsafe.Pointer(&result.anon0))
		proof := &VerifiedChangeProof{
			handle: newHandle(ptr, func(p *C.VerifiedChangeProofContext) C.VoidResult {
				return C.fwd_free_verified_change_proof(p)
			}),
			db: db,
		}
		if err := proof.lease.attach(db.keepAlives, proof.Drop); err != nil {
			return nil, err
		}
		runtime.AddCleanup(proof, drop[*C.VerifiedChangeProofContext], proof.handle)
		return proof, nil
	case C.VerifiedChangeProofResult_Err:
		return nil, newOwnedBytes(*(*C.OwnedBytes)(unsafe.Pointer(&result.anon0))).intoError()
	default:
		return nil, fmt.Errorf("unknown C.VerifiedChangeProofResult tag: %d", result.tag)
	}
}
