[
  {
    "include": [
      "**/**/*.rs"
    ],
    "exclude": [
      "target/**",
      "**/LICENSE*",
      "rpc/**",
      "**/README*",
      "**/Cargo.toml",
      "libaio/**",
      "docs/**"
    ],
    "license": "./.github/license-header.txt"
  }
]
