[
  {
    "include": [
      "**/**/*.rs"
    ],
    "exclude": [
      "target/**",
      "**LICENSE*",
      "rpc**",
      "**README*",
      "**Cargo.toml",
      "Cargo.toml",
      "libaio/**",
      "docs/**/*"
    ],
    "license": "./.github/license-header.txt"
  },
  {
    "include": [
      "target/**",
      "**LICENSE*",
      "rpc**",
      "**README*",
      "**Cargo.toml",
      "Cargo.toml",
      "libaio/**",
      "docs/**/*"
    ],
  }
]
