[
  {
    "include": [
      "**/**/*.rs"
    ],
    "exclude": [
      "target/**",
      "rpc**",
    ],
    "license": "./.github/license-header.txt"
  },
  {
    "include": [
      "target/**",
      "*/LICENSE*",
      "rpc/**",
      "README*",
      "*/README*",
      "Cargo.toml"
      "*/Cargo.toml",
      "libaio/**",
      "docs/**"
      "CODEOWNERS",
    ],
  }
]
