[
  {
    "include": [
      "**/**/*.rs",
      "**/**/*.go",
      "**/**/*.h",
    ],
    "exclude": [
      "target/**",
      "*/LICENSE*",
      "LICENSE.md",
      "RELEASE.md",
      "grpc-testtool/**",
      "README*",
      "**/README*",
      "Cargo.toml",
      "*/Cargo.toml",
      "docs/**",
      "CODEOWNERS",
      "CONTRIBUTING.md",
      "benchmark/**",
      "triehash/**",
      "CHANGELOG.md",
      "cliff.toml",
      "clippy.toml",
      "**/tests/compile_*/**",
      "**/go.mod",
      "**/go.mod",
      "**/cbindgen.toml",
    ],
    "license": "./.github/license-header.txt"
  },
  {
    "include": [
      "target/**",
      "*/LICENSE*",
      "LICENSE.md",
      "RELEASE.md",
      "grpc-testtool/**",
      "README*",
      "**/README*",
      "Cargo.toml",
      "*/Cargo.toml",
      "docs/**",
      "benchmark/**",
      "ffi/**",
      "CODEOWNERS",
      "CONTRIBUTING.md",
      "triehash/**",
      "CHANGELOG.md",
      "cliff.toml",
      "clippy.toml",
      "**/tests/compile_*/**",
    ],
  }
]
