[package]
name = "rpc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
test = false
bench = false

[[bin]]
name = "client"
test = false
bench = false

[dependencies]
firewood = { version = "0.0.3", path = "../firewood" }
prost = "0.11.9"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["sync", "rt-multi-thread"] }
tonic = { version = "0.9.2", features = ["tls"] }

[build-dependencies]
tonic-build = "0.9.2"
