// Copyright (C) 2025, Ava Labs, Inc. All rights reserved.
// See the file LICENSE.md for licensing terms.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: remote.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchOperation_OpType int32

const (
	BatchOperation_PUT           BatchOperation_OpType = 0
	BatchOperation_DELETE        BatchOperation_OpType = 1
	BatchOperation_PREFIX_DELETE BatchOperation_OpType = 2
)

// Enum value maps for BatchOperation_OpType.
var (
	BatchOperation_OpType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
		2: "PREFIX_DELETE",
	}
	BatchOperation_OpType_value = map[string]int32{
		"PUT":           0,
		"DELETE":        1,
		"PREFIX_DELETE": 2,
	}
)

func (x BatchOperation_OpType) Enum() *BatchOperation_OpType {
	p := new(BatchOperation_OpType)
	*p = x
	return p
}

func (x BatchOperation_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BatchOperation_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_remote_proto_enumTypes[0].Descriptor()
}

func (BatchOperation_OpType) Type() protoreflect.EnumType {
	return &file_remote_proto_enumTypes[0]
}

func (x BatchOperation_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BatchOperation_OpType.Descriptor instead.
func (BatchOperation_OpType) EnumDescriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{4, 0}
}

type GetTruncatedTrieRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte root hash identifying the revision.
	RootHash []byte `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// Truncation depth in nibble levels.
	Depth         uint32 `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTruncatedTrieRequest) Reset() {
	*x = GetTruncatedTrieRequest{}
	mi := &file_remote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTruncatedTrieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTruncatedTrieRequest) ProtoMessage() {}

func (x *GetTruncatedTrieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTruncatedTrieRequest.ProtoReflect.Descriptor instead.
func (*GetTruncatedTrieRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{0}
}

func (x *GetTruncatedTrieRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *GetTruncatedTrieRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type GetTruncatedTrieResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Serialized TruncatedTrie (produced by TruncatedTrie.MarshalBinary).
	TrieData      []byte `protobuf:"bytes,1,opt,name=trie_data,json=trieData,proto3" json:"trie_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTruncatedTrieResponse) Reset() {
	*x = GetTruncatedTrieResponse{}
	mi := &file_remote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTruncatedTrieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTruncatedTrieResponse) ProtoMessage() {}

func (x *GetTruncatedTrieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTruncatedTrieResponse.ProtoReflect.Descriptor instead.
func (*GetTruncatedTrieResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{1}
}

func (x *GetTruncatedTrieResponse) GetTrieData() []byte {
	if x != nil {
		return x.TrieData
	}
	return nil
}

type GetValueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte root hash identifying the revision to read from.
	RootHash []byte `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// The key to look up.
	Key           []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_remote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{2}
}

func (x *GetValueRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *GetValueRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetValueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value associated with the key. Empty if the key was not found.
	Value []byte `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// Serialized single-key Merkle proof.
	Proof         []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_remote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{3}
}

func (x *GetValueResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetValueResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type BatchOperation struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	OpType BatchOperation_OpType  `protobuf:"varint,1,opt,name=op_type,json=opType,proto3,enum=firewood.remote.BatchOperation_OpType" json:"op_type,omitempty"`
	Key    []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Value payload; empty for DELETE operations.
	Value         []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperation) Reset() {
	*x = BatchOperation{}
	mi := &file_remote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperation) ProtoMessage() {}

func (x *BatchOperation) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperation.ProtoReflect.Descriptor instead.
func (*BatchOperation) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{4}
}

func (x *BatchOperation) GetOpType() BatchOperation_OpType {
	if x != nil {
		return x.OpType
	}
	return BatchOperation_PUT
}

func (x *BatchOperation) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *BatchOperation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CreateProposalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 32-byte root hash of the base revision.
	RootHash []byte `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// The batch operations to propose.
	Ops []*BatchOperation `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	// Client's truncation depth for witness generation.
	Depth uint32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	// Optional parent proposal ID for chained proposals.
	ParentProposalId *uint64 `protobuf:"varint,4,opt,name=parent_proposal_id,json=parentProposalId,proto3,oneof" json:"parent_proposal_id,omitempty"`
	// Validator ID for multi-head server. Ignored by single-head servers.
	ValidatorId   *uint64 `protobuf:"varint,5,opt,name=validator_id,json=validatorId,proto3,oneof" json:"validator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProposalRequest) Reset() {
	*x = CreateProposalRequest{}
	mi := &file_remote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProposalRequest) ProtoMessage() {}

func (x *CreateProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProposalRequest.ProtoReflect.Descriptor instead.
func (*CreateProposalRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{5}
}

func (x *CreateProposalRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *CreateProposalRequest) GetOps() []*BatchOperation {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *CreateProposalRequest) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *CreateProposalRequest) GetParentProposalId() uint64 {
	if x != nil && x.ParentProposalId != nil {
		return *x.ParentProposalId
	}
	return 0
}

func (x *CreateProposalRequest) GetValidatorId() uint64 {
	if x != nil && x.ValidatorId != nil {
		return *x.ValidatorId
	}
	return 0
}

type CreateProposalResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned proposal identifier.
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// 32-byte root hash after applying the batch operations.
	NewRootHash []byte `protobuf:"bytes,2,opt,name=new_root_hash,json=newRootHash,proto3" json:"new_root_hash,omitempty"`
	// Serialized WitnessProof (produced by WitnessProof.MarshalBinary).
	WitnessProof  []byte `protobuf:"bytes,3,opt,name=witness_proof,json=witnessProof,proto3" json:"witness_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProposalResponse) Reset() {
	*x = CreateProposalResponse{}
	mi := &file_remote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProposalResponse) ProtoMessage() {}

func (x *CreateProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProposalResponse.ProtoReflect.Descriptor instead.
func (*CreateProposalResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{6}
}

func (x *CreateProposalResponse) GetProposalId() uint64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *CreateProposalResponse) GetNewRootHash() []byte {
	if x != nil {
		return x.NewRootHash
	}
	return nil
}

func (x *CreateProposalResponse) GetWitnessProof() []byte {
	if x != nil {
		return x.WitnessProof
	}
	return nil
}

type CommitProposalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The proposal identifier returned by CreateProposal.
	ProposalId    uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitProposalRequest) Reset() {
	*x = CommitProposalRequest{}
	mi := &file_remote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitProposalRequest) ProtoMessage() {}

func (x *CommitProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitProposalRequest.ProtoReflect.Descriptor instead.
func (*CommitProposalRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{7}
}

func (x *CommitProposalRequest) GetProposalId() uint64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

type CommitProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitProposalResponse) Reset() {
	*x = CommitProposalResponse{}
	mi := &file_remote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitProposalResponse) ProtoMessage() {}

func (x *CommitProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitProposalResponse.ProtoReflect.Descriptor instead.
func (*CommitProposalResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{8}
}

type DropProposalRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The proposal identifier to drop.
	ProposalId    uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropProposalRequest) Reset() {
	*x = DropProposalRequest{}
	mi := &file_remote_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropProposalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropProposalRequest) ProtoMessage() {}

func (x *DropProposalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropProposalRequest.ProtoReflect.Descriptor instead.
func (*DropProposalRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{9}
}

func (x *DropProposalRequest) GetProposalId() uint64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

type DropProposalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropProposalResponse) Reset() {
	*x = DropProposalResponse{}
	mi := &file_remote_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropProposalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropProposalResponse) ProtoMessage() {}

func (x *DropProposalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropProposalResponse.ProtoReflect.Descriptor instead.
func (*DropProposalResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{10}
}

type IterBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The proposal to iterate over.
	ProposalId uint64 `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// Start iteration at the first key >= start_key.
	StartKey []byte `protobuf:"bytes,2,opt,name=start_key,json=startKey,proto3" json:"start_key,omitempty"`
	// Maximum number of key-value pairs to return.
	BatchSize uint32 `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// 32-byte root hash for range proof generation. If provided, the response
	// will include a serialized range proof covering this batch.
	RootHash      []byte `protobuf:"bytes,4,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IterBatchRequest) Reset() {
	*x = IterBatchRequest{}
	mi := &file_remote_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IterBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IterBatchRequest) ProtoMessage() {}

func (x *IterBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IterBatchRequest.ProtoReflect.Descriptor instead.
func (*IterBatchRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{11}
}

func (x *IterBatchRequest) GetProposalId() uint64 {
	if x != nil {
		return x.ProposalId
	}
	return 0
}

func (x *IterBatchRequest) GetStartKey() []byte {
	if x != nil {
		return x.StartKey
	}
	return nil
}

func (x *IterBatchRequest) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *IterBatchRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_remote_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{12}
}

func (x *KeyValuePair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValuePair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_remote_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{13}
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned unique validator identifier.
	ValidatorId uint64 `protobuf:"varint,1,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	// 32-byte root hash of the assigned head.
	RootHash      []byte `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_remote_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterResponse) GetValidatorId() uint64 {
	if x != nil {
		return x.ValidatorId
	}
	return 0
}

func (x *RegisterResponse) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

type DeregisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The validator identifier to deregister.
	ValidatorId   uint64 `protobuf:"varint,1,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_remote_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{15}
}

func (x *DeregisterRequest) GetValidatorId() uint64 {
	if x != nil {
		return x.ValidatorId
	}
	return 0
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_remote_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{16}
}

type AdvanceToHashRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The validator identifier.
	ValidatorId uint64 `protobuf:"varint,1,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	// 32-byte root hash to advance to.
	RootHash      []byte `protobuf:"bytes,2,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvanceToHashRequest) Reset() {
	*x = AdvanceToHashRequest{}
	mi := &file_remote_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceToHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceToHashRequest) ProtoMessage() {}

func (x *AdvanceToHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceToHashRequest.ProtoReflect.Descriptor instead.
func (*AdvanceToHashRequest) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{17}
}

func (x *AdvanceToHashRequest) GetValidatorId() uint64 {
	if x != nil {
		return x.ValidatorId
	}
	return 0
}

func (x *AdvanceToHashRequest) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

type AdvanceToHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvanceToHashResponse) Reset() {
	*x = AdvanceToHashResponse{}
	mi := &file_remote_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvanceToHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvanceToHashResponse) ProtoMessage() {}

func (x *AdvanceToHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvanceToHashResponse.ProtoReflect.Descriptor instead.
func (*AdvanceToHashResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{18}
}

type IterBatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The key-value pairs in this batch.
	Pairs []*KeyValuePair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	// True if there are more pairs beyond this batch.
	HasMore bool `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// Serialized range proof covering this batch. Present only when root_hash
	// was provided in the request.
	RangeProof    []byte `protobuf:"bytes,3,opt,name=range_proof,json=rangeProof,proto3" json:"range_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IterBatchResponse) Reset() {
	*x = IterBatchResponse{}
	mi := &file_remote_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IterBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IterBatchResponse) ProtoMessage() {}

func (x *IterBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remote_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IterBatchResponse.ProtoReflect.Descriptor instead.
func (*IterBatchResponse) Descriptor() ([]byte, []int) {
	return file_remote_proto_rawDescGZIP(), []int{19}
}

func (x *IterBatchResponse) GetPairs() []*KeyValuePair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *IterBatchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *IterBatchResponse) GetRangeProof() []byte {
	if x != nil {
		return x.RangeProof
	}
	return nil
}

var File_remote_proto protoreflect.FileDescriptor

const file_remote_proto_rawDesc = "" +
	"\n" +
	"\fremote.proto\x12\x0ffirewood.remote\"L\n" +
	"\x17GetTruncatedTrieRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\fR\brootHash\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\rR\x05depth\"7\n" +
	"\x18GetTruncatedTrieResponse\x12\x1b\n" +
	"\ttrie_data\x18\x01 \x01(\fR\btrieData\"@\n" +
	"\x0fGetValueRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\fR\brootHash\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"M\n" +
	"\x10GetValueResponse\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proofB\b\n" +
	"\x06_value\"\xab\x01\n" +
	"\x0eBatchOperation\x12?\n" +
	"\aop_type\x18\x01 \x01(\x0e2&.firewood.remote.BatchOperation.OpTypeR\x06opType\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"0\n" +
	"\x06OpType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\x11\n" +
	"\rPREFIX_DELETE\x10\x02\"\x80\x02\n" +
	"\x15CreateProposalRequest\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\fR\brootHash\x121\n" +
	"\x03ops\x18\x02 \x03(\v2\x1f.firewood.remote.BatchOperationR\x03ops\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\rR\x05depth\x121\n" +
	"\x12parent_proposal_id\x18\x04 \x01(\x04H\x00R\x10parentProposalId\x88\x01\x01\x12&\n" +
	"\fvalidator_id\x18\x05 \x01(\x04H\x01R\vvalidatorId\x88\x01\x01B\x15\n" +
	"\x13_parent_proposal_idB\x0f\n" +
	"\r_validator_id\"\x82\x01\n" +
	"\x16CreateProposalResponse\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x04R\n" +
	"proposalId\x12\"\n" +
	"\rnew_root_hash\x18\x02 \x01(\fR\vnewRootHash\x12#\n" +
	"\rwitness_proof\x18\x03 \x01(\fR\fwitnessProof\"8\n" +
	"\x15CommitProposalRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x04R\n" +
	"proposalId\"\x18\n" +
	"\x16CommitProposalResponse\"6\n" +
	"\x13DropProposalRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x04R\n" +
	"proposalId\"\x16\n" +
	"\x14DropProposalResponse\"\x8c\x01\n" +
	"\x10IterBatchRequest\x12\x1f\n" +
	"\vproposal_id\x18\x01 \x01(\x04R\n" +
	"proposalId\x12\x1b\n" +
	"\tstart_key\x18\x02 \x01(\fR\bstartKey\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\rR\tbatchSize\x12\x1b\n" +
	"\troot_hash\x18\x04 \x01(\fR\brootHash\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x11\n" +
	"\x0fRegisterRequest\"R\n" +
	"\x10RegisterResponse\x12!\n" +
	"\fvalidator_id\x18\x01 \x01(\x04R\vvalidatorId\x12\x1b\n" +
	"\troot_hash\x18\x02 \x01(\fR\brootHash\"6\n" +
	"\x11DeregisterRequest\x12!\n" +
	"\fvalidator_id\x18\x01 \x01(\x04R\vvalidatorId\"\x14\n" +
	"\x12DeregisterResponse\"V\n" +
	"\x14AdvanceToHashRequest\x12!\n" +
	"\fvalidator_id\x18\x01 \x01(\x04R\vvalidatorId\x12\x1b\n" +
	"\troot_hash\x18\x02 \x01(\fR\brootHash\"\x17\n" +
	"\x15AdvanceToHashResponse\"\x84\x01\n" +
	"\x11IterBatchResponse\x123\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1d.firewood.remote.KeyValuePairR\x05pairs\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vrange_proof\x18\x03 \x01(\fR\n" +
	"rangeProof2\xc9\x06\n" +
	"\x0eFirewoodRemote\x12g\n" +
	"\x10GetTruncatedTrie\x12(.firewood.remote.GetTruncatedTrieRequest\x1a).firewood.remote.GetTruncatedTrieResponse\x12O\n" +
	"\bGetValue\x12 .firewood.remote.GetValueRequest\x1a!.firewood.remote.GetValueResponse\x12a\n" +
	"\x0eCreateProposal\x12&.firewood.remote.CreateProposalRequest\x1a'.firewood.remote.CreateProposalResponse\x12a\n" +
	"\x0eCommitProposal\x12&.firewood.remote.CommitProposalRequest\x1a'.firewood.remote.CommitProposalResponse\x12[\n" +
	"\fDropProposal\x12$.firewood.remote.DropProposalRequest\x1a%.firewood.remote.DropProposalResponse\x12R\n" +
	"\tIterBatch\x12!.firewood.remote.IterBatchRequest\x1a\".firewood.remote.IterBatchResponse\x12O\n" +
	"\bRegister\x12 .firewood.remote.RegisterRequest\x1a!.firewood.remote.RegisterResponse\x12U\n" +
	"\n" +
	"Deregister\x12\".firewood.remote.DeregisterRequest\x1a#.firewood.remote.DeregisterResponse\x12^\n" +
	"\rAdvanceToHash\x12%.firewood.remote.AdvanceToHashRequest\x1a&.firewood.remote.AdvanceToHashResponseB/Z-github.com/ava-labs/firewood/ffi/remote/protob\x06proto3"

var (
	file_remote_proto_rawDescOnce sync.Once
	file_remote_proto_rawDescData []byte
)

func file_remote_proto_rawDescGZIP() []byte {
	file_remote_proto_rawDescOnce.Do(func() {
		file_remote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remote_proto_rawDesc), len(file_remote_proto_rawDesc)))
	})
	return file_remote_proto_rawDescData
}

var file_remote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_remote_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_remote_proto_goTypes = []any{
	(BatchOperation_OpType)(0),       // 0: firewood.remote.BatchOperation.OpType
	(*GetTruncatedTrieRequest)(nil),  // 1: firewood.remote.GetTruncatedTrieRequest
	(*GetTruncatedTrieResponse)(nil), // 2: firewood.remote.GetTruncatedTrieResponse
	(*GetValueRequest)(nil),          // 3: firewood.remote.GetValueRequest
	(*GetValueResponse)(nil),         // 4: firewood.remote.GetValueResponse
	(*BatchOperation)(nil),           // 5: firewood.remote.BatchOperation
	(*CreateProposalRequest)(nil),    // 6: firewood.remote.CreateProposalRequest
	(*CreateProposalResponse)(nil),   // 7: firewood.remote.CreateProposalResponse
	(*CommitProposalRequest)(nil),    // 8: firewood.remote.CommitProposalRequest
	(*CommitProposalResponse)(nil),   // 9: firewood.remote.CommitProposalResponse
	(*DropProposalRequest)(nil),      // 10: firewood.remote.DropProposalRequest
	(*DropProposalResponse)(nil),     // 11: firewood.remote.DropProposalResponse
	(*IterBatchRequest)(nil),         // 12: firewood.remote.IterBatchRequest
	(*KeyValuePair)(nil),             // 13: firewood.remote.KeyValuePair
	(*RegisterRequest)(nil),          // 14: firewood.remote.RegisterRequest
	(*RegisterResponse)(nil),         // 15: firewood.remote.RegisterResponse
	(*DeregisterRequest)(nil),        // 16: firewood.remote.DeregisterRequest
	(*DeregisterResponse)(nil),       // 17: firewood.remote.DeregisterResponse
	(*AdvanceToHashRequest)(nil),     // 18: firewood.remote.AdvanceToHashRequest
	(*AdvanceToHashResponse)(nil),    // 19: firewood.remote.AdvanceToHashResponse
	(*IterBatchResponse)(nil),        // 20: firewood.remote.IterBatchResponse
}
var file_remote_proto_depIdxs = []int32{
	0,  // 0: firewood.remote.BatchOperation.op_type:type_name -> firewood.remote.BatchOperation.OpType
	5,  // 1: firewood.remote.CreateProposalRequest.ops:type_name -> firewood.remote.BatchOperation
	13, // 2: firewood.remote.IterBatchResponse.pairs:type_name -> firewood.remote.KeyValuePair
	1,  // 3: firewood.remote.FirewoodRemote.GetTruncatedTrie:input_type -> firewood.remote.GetTruncatedTrieRequest
	3,  // 4: firewood.remote.FirewoodRemote.GetValue:input_type -> firewood.remote.GetValueRequest
	6,  // 5: firewood.remote.FirewoodRemote.CreateProposal:input_type -> firewood.remote.CreateProposalRequest
	8,  // 6: firewood.remote.FirewoodRemote.CommitProposal:input_type -> firewood.remote.CommitProposalRequest
	10, // 7: firewood.remote.FirewoodRemote.DropProposal:input_type -> firewood.remote.DropProposalRequest
	12, // 8: firewood.remote.FirewoodRemote.IterBatch:input_type -> firewood.remote.IterBatchRequest
	14, // 9: firewood.remote.FirewoodRemote.Register:input_type -> firewood.remote.RegisterRequest
	16, // 10: firewood.remote.FirewoodRemote.Deregister:input_type -> firewood.remote.DeregisterRequest
	18, // 11: firewood.remote.FirewoodRemote.AdvanceToHash:input_type -> firewood.remote.AdvanceToHashRequest
	2,  // 12: firewood.remote.FirewoodRemote.GetTruncatedTrie:output_type -> firewood.remote.GetTruncatedTrieResponse
	4,  // 13: firewood.remote.FirewoodRemote.GetValue:output_type -> firewood.remote.GetValueResponse
	7,  // 14: firewood.remote.FirewoodRemote.CreateProposal:output_type -> firewood.remote.CreateProposalResponse
	9,  // 15: firewood.remote.FirewoodRemote.CommitProposal:output_type -> firewood.remote.CommitProposalResponse
	11, // 16: firewood.remote.FirewoodRemote.DropProposal:output_type -> firewood.remote.DropProposalResponse
	20, // 17: firewood.remote.FirewoodRemote.IterBatch:output_type -> firewood.remote.IterBatchResponse
	15, // 18: firewood.remote.FirewoodRemote.Register:output_type -> firewood.remote.RegisterResponse
	17, // 19: firewood.remote.FirewoodRemote.Deregister:output_type -> firewood.remote.DeregisterResponse
	19, // 20: firewood.remote.FirewoodRemote.AdvanceToHash:output_type -> firewood.remote.AdvanceToHashResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_remote_proto_init() }
func file_remote_proto_init() {
	if File_remote_proto != nil {
		return
	}
	file_remote_proto_msgTypes[3].OneofWrappers = []any{}
	file_remote_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remote_proto_rawDesc), len(file_remote_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_remote_proto_goTypes,
		DependencyIndexes: file_remote_proto_depIdxs,
		EnumInfos:         file_remote_proto_enumTypes,
		MessageInfos:      file_remote_proto_msgTypes,
	}.Build()
	File_remote_proto = out.File
	file_remote_proto_goTypes = nil
	file_remote_proto_depIdxs = nil
}
