// Copyright (C) 2025, Ava Labs, Inc. All rights reserved.
// See the file LICENSE.md for licensing terms.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/remote.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FirewoodRemote_GetTruncatedTrie_FullMethodName = "/firewood.remote.FirewoodRemote/GetTruncatedTrie"
	FirewoodRemote_GetValue_FullMethodName         = "/firewood.remote.FirewoodRemote/GetValue"
	FirewoodRemote_CreateProposal_FullMethodName   = "/firewood.remote.FirewoodRemote/CreateProposal"
	FirewoodRemote_CommitProposal_FullMethodName   = "/firewood.remote.FirewoodRemote/CommitProposal"
	FirewoodRemote_DropProposal_FullMethodName     = "/firewood.remote.FirewoodRemote/DropProposal"
	FirewoodRemote_IterBatch_FullMethodName        = "/firewood.remote.FirewoodRemote/IterBatch"
)

// FirewoodRemoteClient is the client API for FirewoodRemote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirewoodRemoteClient interface {
	// Bootstrap: get a truncated trie for a given root hash.
	GetTruncatedTrie(ctx context.Context, in *GetTruncatedTrieRequest, opts ...grpc.CallOption) (*GetTruncatedTrieResponse, error)
	// Read: get a value with its Merkle proof.
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error)
	// Write: two-phase commit.
	CreateProposal(ctx context.Context, in *CreateProposalRequest, opts ...grpc.CallOption) (*CreateProposalResponse, error)
	CommitProposal(ctx context.Context, in *CommitProposalRequest, opts ...grpc.CallOption) (*CommitProposalResponse, error)
	// Drop a pending proposal without committing.
	DropProposal(ctx context.Context, in *DropProposalRequest, opts ...grpc.CallOption) (*DropProposalResponse, error)
	// Paginated iteration over a proposal's key-value pairs.
	IterBatch(ctx context.Context, in *IterBatchRequest, opts ...grpc.CallOption) (*IterBatchResponse, error)
}

type firewoodRemoteClient struct {
	cc grpc.ClientConnInterface
}

func NewFirewoodRemoteClient(cc grpc.ClientConnInterface) FirewoodRemoteClient {
	return &firewoodRemoteClient{cc}
}

func (c *firewoodRemoteClient) GetTruncatedTrie(ctx context.Context, in *GetTruncatedTrieRequest, opts ...grpc.CallOption) (*GetTruncatedTrieResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTruncatedTrieResponse)
	err := c.cc.Invoke(ctx, FirewoodRemote_GetTruncatedTrie_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewoodRemoteClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*GetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, FirewoodRemote_GetValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewoodRemoteClient) CreateProposal(ctx context.Context, in *CreateProposalRequest, opts ...grpc.CallOption) (*CreateProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProposalResponse)
	err := c.cc.Invoke(ctx, FirewoodRemote_CreateProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewoodRemoteClient) CommitProposal(ctx context.Context, in *CommitProposalRequest, opts ...grpc.CallOption) (*CommitProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitProposalResponse)
	err := c.cc.Invoke(ctx, FirewoodRemote_CommitProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewoodRemoteClient) DropProposal(ctx context.Context, in *DropProposalRequest, opts ...grpc.CallOption) (*DropProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropProposalResponse)
	err := c.cc.Invoke(ctx, FirewoodRemote_DropProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firewoodRemoteClient) IterBatch(ctx context.Context, in *IterBatchRequest, opts ...grpc.CallOption) (*IterBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IterBatchResponse)
	err := c.cc.Invoke(ctx, FirewoodRemote_IterBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirewoodRemoteServer is the server API for FirewoodRemote service.
// All implementations must embed UnimplementedFirewoodRemoteServer
// for forward compatibility.
type FirewoodRemoteServer interface {
	// Bootstrap: get a truncated trie for a given root hash.
	GetTruncatedTrie(context.Context, *GetTruncatedTrieRequest) (*GetTruncatedTrieResponse, error)
	// Read: get a value with its Merkle proof.
	GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error)
	// Write: two-phase commit.
	CreateProposal(context.Context, *CreateProposalRequest) (*CreateProposalResponse, error)
	CommitProposal(context.Context, *CommitProposalRequest) (*CommitProposalResponse, error)
	// Drop a pending proposal without committing.
	DropProposal(context.Context, *DropProposalRequest) (*DropProposalResponse, error)
	// Paginated iteration over a proposal's key-value pairs.
	IterBatch(context.Context, *IterBatchRequest) (*IterBatchResponse, error)
	mustEmbedUnimplementedFirewoodRemoteServer()
}

// UnimplementedFirewoodRemoteServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFirewoodRemoteServer struct{}

func (UnimplementedFirewoodRemoteServer) GetTruncatedTrie(context.Context, *GetTruncatedTrieRequest) (*GetTruncatedTrieResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTruncatedTrie not implemented")
}
func (UnimplementedFirewoodRemoteServer) GetValue(context.Context, *GetValueRequest) (*GetValueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedFirewoodRemoteServer) CreateProposal(context.Context, *CreateProposalRequest) (*CreateProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProposal not implemented")
}
func (UnimplementedFirewoodRemoteServer) CommitProposal(context.Context, *CommitProposalRequest) (*CommitProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitProposal not implemented")
}
func (UnimplementedFirewoodRemoteServer) DropProposal(context.Context, *DropProposalRequest) (*DropProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropProposal not implemented")
}
func (UnimplementedFirewoodRemoteServer) IterBatch(context.Context, *IterBatchRequest) (*IterBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IterBatch not implemented")
}
func (UnimplementedFirewoodRemoteServer) mustEmbedUnimplementedFirewoodRemoteServer() {}
func (UnimplementedFirewoodRemoteServer) testEmbeddedByValue()                        {}

// UnsafeFirewoodRemoteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirewoodRemoteServer will
// result in compilation errors.
type UnsafeFirewoodRemoteServer interface {
	mustEmbedUnimplementedFirewoodRemoteServer()
}

func RegisterFirewoodRemoteServer(s grpc.ServiceRegistrar, srv FirewoodRemoteServer) {
	// If the following call panics, it indicates UnimplementedFirewoodRemoteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FirewoodRemote_ServiceDesc, srv)
}

func _FirewoodRemote_GetTruncatedTrie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTruncatedTrieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewoodRemoteServer).GetTruncatedTrie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewoodRemote_GetTruncatedTrie_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewoodRemoteServer).GetTruncatedTrie(ctx, req.(*GetTruncatedTrieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewoodRemote_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewoodRemoteServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewoodRemote_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewoodRemoteServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewoodRemote_CreateProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewoodRemoteServer).CreateProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewoodRemote_CreateProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewoodRemoteServer).CreateProposal(ctx, req.(*CreateProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewoodRemote_CommitProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewoodRemoteServer).CommitProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewoodRemote_CommitProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewoodRemoteServer).CommitProposal(ctx, req.(*CommitProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewoodRemote_DropProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewoodRemoteServer).DropProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewoodRemote_DropProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewoodRemoteServer).DropProposal(ctx, req.(*DropProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirewoodRemote_IterBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IterBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirewoodRemoteServer).IterBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FirewoodRemote_IterBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirewoodRemoteServer).IterBatch(ctx, req.(*IterBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FirewoodRemote_ServiceDesc is the grpc.ServiceDesc for FirewoodRemote service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirewoodRemote_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "firewood.remote.FirewoodRemote",
	HandlerType: (*FirewoodRemoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTruncatedTrie",
			Handler:    _FirewoodRemote_GetTruncatedTrie_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _FirewoodRemote_GetValue_Handler,
		},
		{
			MethodName: "CreateProposal",
			Handler:    _FirewoodRemote_CreateProposal_Handler,
		},
		{
			MethodName: "CommitProposal",
			Handler:    _FirewoodRemote_CommitProposal_Handler,
		},
		{
			MethodName: "DropProposal",
			Handler:    _FirewoodRemote_DropProposal_Handler,
		},
		{
			MethodName: "IterBatch",
			Handler:    _FirewoodRemote_IterBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/remote.proto",
}
