# Launch Stages Configuration

packages:
  - git
  - build-essential
  - curl
  - protobuf-compiler
  - make
  - apt-transport-https
  - net-tools
  - unzip
users:
  - name: rkuris
    groups: "users, adm, sudo"
    shell: /usr/bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL2RVmfpoKYi0tJd2DhQEp8tB3m2PSuaYxIfnLwqt03u cardno:23_537_110 ron"
  - name: austin
    groups: "users, adm, sudo"
    shell: /usr/bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICoGgX8nCin3FPc1V3YYN1M9g039wMbzZSAXZJCqzBt3 cardno:31_786_961 austin"
  - name: aaron
    groups: "users, adm, sudo"
    shell: /usr/bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMj2j6ySwsFx7Y6FW2UXlkjCZfFDQKHWh0GTBjkK9ruV cardno:19_236_959 aaron"
  - name: brandon
    groups: "users, adm, sudo"
    shell: /usr/bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHWuCq/y50S0yFPJQEAifeeN4n6EL3IlUuYbAdk2w2kL cardno:33_731_913 brandon"
  - name: amin
    groups: "users, adm, sudo"
    shell: /usr/bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE8iR1X8/ELrzjczZvCkrTGCEoN6/dtlP01QFGuUpYxV cardno:33_317_839 amin"
  - name: bernard
    groups: "users, adm, sudo"
    shell: /usr/bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE/1C8JVL0g6qqMw1p0TwJMqJqERxYTX+7PnP+gXP4km cardno:19_155_748 bernard"
  - name: rodrigo
    groups: "users, adm, sudo"
    shell: /usr/bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDT0/IE2kLNpvaELug1zppQGY03z3fe2zOTjyS655Sgq cardno:28_650_437 rodrigo"

variables:
  nvme_base: "/mnt/nvme"
  firewood_repo: "https://github.com/ava-labs/firewood.git"
  avalanchego_repo: "https://github.com/ava-labs/avalanchego.git"
  coreth_repo: "https://github.com/ava-labs/coreth.git"
  libevm_repo: "https://github.com/ava-labs/libevm.git"
  s3_bucket: "avalanchego-bootstrap-testing"

stages:
  rust-install:
    name: "Installing Rust"
    commands:
      - "echo 'PATH=/usr/local/go/bin:$HOME/.cargo/bin:$PATH' >> ~ubuntu/.profile"
      - "curl https://sh.rustup.rs -sSf | RUSTUP_HOME=/usr/local/rust CARGO_HOME=/usr/local/rust sh -s -- -y --no-modify-path"
      - "sudo -u ubuntu --login rustup default stable"
  ssm-agent:
    name: "Installing SSM Agent"
    commands:
      - "snap install amazon-ssm-agent --classic"
      - "systemctl start snap.amazon-ssm-agent.amazon-ssm-agent"
      - "systemctl enable snap.amazon-ssm-agent.amazon-ssm-agent"
  clone-firewood:
    name: "Cloning firewood"
    commands:
      - "git clone --depth 1 {{ branches.firewood }} {{ variables.firewood_repo }} /tmp/firewood"
  setup-environment:
    name: "Setting up environment"
    commands:
      - "bash /tmp/firewood/benchmark/setup-scripts/build-environment.sh"
      - "bash -c 'mkdir ~ubuntu/firewood; mv /tmp/firewood/{.[!.],}* ~ubuntu/firewood/'"
      - "chown -R ubuntu:users {{ variables.nvme_base }}/ubuntu"
      - "chmod -R g=u {{ variables.nvme_base }}/ubuntu"
      - "find {{ variables.nvme_base }}/ubuntu -type d -print0 | xargs -0 chmod g+s"
      - "sudo -u ubuntu ln -s {{ variables.nvme_base }}/ubuntu/data /home/ubuntu/data"
      - "sudo -u ubuntu ln -s {{ variables.nvme_base }}/ubuntu/avalanchego /home/ubuntu/avalanchego"
  install-go-grafana:
    name: "Installing Go and Grafana"
    commands:
      - "bash {{ variables.nvme_base }}/ubuntu/firewood/benchmark/setup-scripts/install-golang.sh"
      - "bash {{ variables.nvme_base }}/ubuntu/firewood/benchmark/setup-scripts/install-grafana.sh"
  clone-repos:
    name: "Cloning repositories"
    commands:
      - "snap install task --classic"
      - "sudo -u ubuntu -D {{ variables.nvme_base }}/ubuntu git clone --depth 100 {{ branches.avalanchego }} {{ variables.avalanchego_repo }}"
      - "sudo -u ubuntu -D {{ variables.nvme_base }}/ubuntu git clone --depth 100 {{ branches.libevm }} {{ variables.libevm_repo }}"
  configure-go-modules:
    name: "Configuring Go modules"
    commands:
      # Configure graft/coreth to use local firewood and libevm
      - "sudo -u ubuntu -D {{ variables.nvme_base }}/ubuntu/avalanchego/graft/coreth /usr/local/go/bin/go mod edit -replace github.com/ava-labs/firewood-go-ethhash/ffi=../../../firewood/ffi"
      - "sudo -u ubuntu -D {{ variables.nvme_base }}/ubuntu/avalanchego/graft/coreth /usr/local/go/bin/go mod edit -replace github.com/ava-labs/libevm=../../../libevm"
      # Configure avalanchego to use local firewood and libevm
      - "sudo -u ubuntu -D {{ variables.nvme_base }}/ubuntu/avalanchego /usr/local/go/bin/go mod edit -replace github.com/ava-labs/firewood-go-ethhash/ffi=../firewood/ffi"
      - "sudo -u ubuntu -D {{ variables.nvme_base }}/ubuntu/avalanchego /usr/local/go/bin/go mod edit -replace github.com/ava-labs/libevm=../libevm"
      # Run go mod tidy for coreth and avalanchego
      - "sudo -u ubuntu --login -D {{ variables.nvme_base }}/ubuntu/avalanchego/graft/coreth go mod tidy"
  build-firewood-ffi:
    name: "Building firewood FFI"
    commands:
      - "sudo -u ubuntu -D {{ variables.nvme_base }}/ubuntu/firewood/ffi --login time cargo build --profile maxperf --features ethhash,logger > {{ variables.nvme_base }}/ubuntu/firewood/build.log 2>&1"
  build-avalanchego:
    name: "Building avalanchego"
    commands:
      - "sudo -u ubuntu --login -D {{ variables.nvme_base }}/ubuntu/avalanchego go mod tidy"
      - "sudo -u ubuntu --login -D {{ variables.nvme_base }}/ubuntu/avalanchego time scripts/build.sh > {{ variables.nvme_base }}/ubuntu/avalanchego/build.log 2>&1"
  install-s5cmd:
    name: "Installing s5cmd"
    commands:
      - |
        S5CMD_URL=$(curl -s https://api.github.com/repos/peak/s5cmd/releases/latest \
          | grep "browser_download_url" \
          | grep "linux_$(dpkg --print-architecture).deb" \
          | cut -d '"' -f 4)
        curl -L -o /tmp/s5cmd.deb "$S5CMD_URL"
        dpkg -i /tmp/s5cmd.deb
  download-blocks:
    name: "Downloading blocks"
    commands:
      - "sudo -u ubuntu mkdir -p {{ variables.nvme_base }}/ubuntu/exec-data/blocks"
      - "s5cmd cp 's3://{{ variables.s3_bucket }}/cchain-mainnet-blocks-{{ args.nblocks }}-ldb/*' {{ variables.nvme_base }}/ubuntu/exec-data/blocks/ >/dev/null"
      - "chown -R ubuntu {{ variables.nvme_base }}/ubuntu/exec-data"
      - "chmod -R g=u {{ variables.nvme_base }}/ubuntu/exec-data"
  init-state-dir:
    name: "Initializing state directory"
    commands:
      - "sudo -u ubuntu mkdir -p {{ variables.nvme_base }}/ubuntu/exec-data/current-state"

scenarios:
  reexecute:
    description: "Full bootstrap execution from block 1 to N"
    stages:
      - rust-install
      - ssm-agent
      - clone-firewood
      - setup-environment
      - install-go-grafana
      - clone-repos
      - configure-go-modules
      - build-firewood-ffi
      - build-avalanchego
      - install-s5cmd
      - download-blocks      
      - init-state-dir
      - execute-range:
          name: "Executing blocks"
          commands:
            - "sudo -u ubuntu -D {{ variables.nvme_base }}/ubuntu/avalanchego --login METRICS_SERVER_ENABLED={{ args.metrics_server }} CURRENT_STATE_DIR={{ variables.nvme_base }}/ubuntu/exec-data/current-state BLOCK_DIR={{ variables.nvme_base }}/ubuntu/exec-data/blocks START_BLOCK=1 END_BLOCK={{ variables.end_block }} CONFIG={{ args.config }} time task test-cchain-reexecution > /var/log/bootstrap{{ variables.tag }}.log 2>&1 &"
