name: Publish Benchmark Result
description: Publish a Go benchmark result via github-action-benchmark

inputs:
  name: { description: "Series name", required: true }
  output-file: { description: "Benchmark output file", required: true }
  ref: { description: "Commit SHA", required: true }
  github-token: { description: "GitHub token", required: true }
  benchmark-data-dir-path:
    { description: "Data dir in reports repo", required: true }
  alert-threshold: { description: "Regression alert threshold", required: true }
  comment-on-alert: { description: "Comment on alerts", required: true }
  fail-on-alert: { description: "Fail on alerts", required: true }
  alert-comment-cc-users: { description: "CC on alert comments", default: "" }
  gh-repository: { description: "Reports repository", required: true }
  gh-pages-branch: { description: "Reports branch", required: true }

runs:
  using: composite
  steps:
    - shell: bash
      run: rm -rf ./benchmark-data-repository
    - uses: benchmark-action/github-action-benchmark@v1
      with:
        name: ${{ inputs.name }}
        tool: go
        output-file-path: ${{ inputs.output-file }}
        ref: ${{ inputs.ref }}
        github-token: ${{ inputs.github-token }}
        auto-push: true
        benchmark-data-dir-path: ${{ inputs.benchmark-data-dir-path }}
        alert-threshold: ${{ inputs.alert-threshold }}
        comment-on-alert: ${{ inputs.comment-on-alert }}
        fail-on-alert: ${{ inputs.fail-on-alert }}
        alert-comment-cc-users: ${{ inputs.alert-comment-cc-users }}
        gh-repository: ${{ inputs.gh-repository }}
        gh-pages-branch: ${{ inputs.gh-pages-branch }}
