[package]
name = "storage"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
bitflags = "2.5.0"
enum-as-inner = "0.6.0"
hex = "0.4.3"
serde = { version = "1.0.199", features = ["derive"] }
smallvec = { version = "1.13.2", features = ["serde", "write", "union"] }
sha2 = "0.10.8"
integer-encoding = "4.0.0"
arc-swap = "1.7.1"
lru = "0.12.4"
metrics = "0.24.0"
log = { version = "0.4.20", optional = true }
bytemuck = "1.7.0"
bytemuck_derive = "1.7.0"
bitfield = "0.17.0"

[dev-dependencies]
rand = "0.8.5"
test-case = "3.3.1"
criterion = { version = "0.5.1", features = ["async_tokio", "html_reports"] }
pprof = { version = "0.14.0", features = ["flamegraph"] }
tempfile = "3.12.0"

[features]
logger = ["log"]
branch_factor_256 = []

[[bench]]
name = "serializer"
harness = false
