[package]
name = "firewood-storage"
version = "0.0.7"
edition = "2024"
rust-version = "1.85.0"
authors = [
     "Aaron Buchwald <aaron.buchwald56@gmail.com>",
     "Ron Kuris <ron.kuris@avalabs.org>",
     "Suyan Qu <36519575+qusuyan@users.noreply.github.com>",
]
description = "Storage layer for Firewood, an embedded key-value store optimized for blockchain state."
license-file = "../LICENSE.md"
homepage = "https://avalabs.org"
repository = "https://github.com/ava-labs/firewood"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = { workspace = true }
bitflags = "2.5.0"
enum-as-inner = "0.6.0"
hex = "0.4.3"
serde = { workspace = true, features = ["derive"] }
smallvec = { workspace = true, features = ["serde", "write", "union"] }
sha2 = { workspace = true }
integer-encoding = { workspace = true }
arc-swap = "1.7.1"
lru = "0.15.0"
metrics = { workspace = true }
log = { version = "0.4.20", optional = true }
bytemuck = "1.7.0"
bytemuck_derive = "1.7.0"
bitfield = "0.19.0"
fastrace = { workspace = true }
io-uring = { version = "0.7.4", optional = true }
triomphe = "0.1.14"
coarsetime = { workspace = true }
rlp = { version = "0.6.1", optional = true }
sha3 = { version = "0.10.8", optional = true }
bytes = { version = "1.10.1", optional = true }
thiserror = { workspace = true }
semver = "1.0.26"

[dev-dependencies]
rand = { workspace = true }
test-case = "3.3.1"
criterion = { workspace = true, features = ["async_tokio", "html_reports"] }
pprof = { workspace = true, features = ["flamegraph"] }
tempfile = { workspace = true }
nonzero_ext = "0.3.0"

[features]
logger = ["log"]
branch_factor_256 = []
io-uring = ["dep:io-uring"]
ethhash = [ "dep:rlp", "dep:sha3", "dep:bytes" ]

[[bench]]
name = "serializer"
harness = false

[lints]
workspace = true
