[package]
name = "storage"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
bitflags = "2.5.0"
enum-as-inner = "0.6.0"
hex = "0.4.3"
serde = { version = "1.0.199", features = ["derive"] }
smallvec = { version = "1.13.2", features = ["serde", "write", "union"] }
sha2 = "0.10.8"
integer-encoding = "4.0.0"

[dev-dependencies]
rand = "0.8.5"
test-case = "3.3.1"
