[package]
name = "firewood-triehash"
version = "0.8.5"
authors = ["Parity Technologies <admin@parity.io>", "Ron Kuris <swcafe@gmail.com>"]
description = "In-memory patricia trie operations"
repository = "https://github.com/paritytech/parity-common"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
hash-db = { version = "0.16.0", default-features = false }
rlp = { version = "0.6", default-features = false }

[dev-dependencies]
criterion = "0.6.0"
keccak-hasher = "0.16.0"
ethereum-types = { version = "0.15.1" }
tiny-keccak = { version = "2.0", features = ["keccak"] }
trie-standardmap = "0.16.0"
hex-literal = "1.0.0"

[features]
default = ["std"]
std = [
	"hash-db/std",
	"rlp/std",
]

[[bench]]
name = "triehash"
path = "benches/triehash.rs"
harness = false
